### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by EnterFor**
Hello!~I added Chinese localization
The alloy is not very easy to express, I chose another way of translation
I hope you can combine them, thanks in advance ~

### CODE REVIEW

**Comment by kwpugh** [comment]
Thank you, I uploaded a new version with the translation.   If you would like to take my Easy Steel and More and Gobber Mod, that would be great.

**Comment by kwpugh** [comment]
What is your curse forge ID, so I can add you as a translator

**Comment by EnterFor** [comment]
image
Ha,Thanks

**Comment by kwpugh** [comment]
Thank you.

**Pull request merged**
